### ISSUE TITLE
Tamalone support voor WerkWel

### ISSUE THREAD

**Issue by FransClements** [tamalone/support#1]
Dag Ritze, 

svp kun je inkomende calls van gebruikers in deze repository als issue registeren:
https://github.com/tamalone/support/issues

We hebben nog een discussie of deze repository ook beschikbaar gemaakt moet worden aan (eind)gebruikers en of de issues wel/niet direct in de development repository gelogd moeten worden en hoe een issue overgezet kan worden van support naar development. 

Echter vooralsnog support dus in deze: Tamalone Support

-- 
Met vriendelijke groet,  

Frans W. Clements
Partner WerkWel
Engelsestadweg 22
3772 TL, Barneveld
Tel.: 06 - 13  75 74 84

**Comment by tamalone** [comment]
Ik neem aan dat deze repo public blijft?  Dus dan geen privacy gevoelige info plaatsen SVP. Houd er rekening mee dat customers ook elkaars issues kunnen zien. Dit kan een voordeel maar ook een nadeel zijn. Deze repo kan ook desgewenst private gemaakt worden voor alleen support medewerkers. Laat even weten wat jullie voorkeur heeft.
